Update scripts.js
Solves error: "Uncaught TypeError: Property '$' of object [object Object] is not a function "

I noticed the js conflict with Wordpress Canvas Shortcuts plugin.