Update scripts.js
Fixed error: "jQuery Uncaught TypeError: Property '$' of object [object Window] is not a function"

I noticed it because it prevents the woocommerce button to appear when selecting a product variation (https://github.com/woothemes/woocommerce/issues/1074)